"""
BakeOps Telegram Alert Service
Sends a formatted alert to the plant manager when a recommendation lands.
Never raises — Telegram failure must never break the demo.
"""
from __future__ import annotations

import os
from datetime import datetime

import httpx

TELEGRAM_BOT_TOKEN: str = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID:   str = os.getenv("TELEGRAM_CHAT_ID",   "")
_API_URL = "https://api.telegram.org/bot{token}/sendMessage"


def _is_configured() -> bool:
    return bool(TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID)


async def send_alert(
    *,
    scenario_title: str,
    diagnosis: str,
    recommended_action: str,
    cost_of_action: str,
    cost_of_inaction: str,
    confidence: float,
    response_time_seconds: int,
) -> bool:
    """Send a formatted recommendation alert to Telegram.
    Returns True if delivered, False otherwise (silent on error).
    """
    if not _is_configured():
        print("[Telegram] Not configured — skipping alert (set TELEGRAM_BOT_TOKEN + TELEGRAM_CHAT_ID)")
        return False

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S EDT")
    ref_id    = f"BO-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    conf_pct  = int(confidence * 100) if confidence <= 1.0 else int(confidence)

    # Escape special Markdown chars that break Telegram
    def _esc(s: str) -> str:
        for ch in r"_*[]()~`>#+-=|{}.!":
            s = s.replace(ch, f"\\{ch}")
        return s

    message = (
        f"🚨 *BAKEOPS ALERT*\n"
        f"━━━━━━━━━━━━━━━━\n"
        f"*{scenario_title}*\n\n"
        f"📋 *Diagnosis*\n"
        f"{diagnosis}\n\n"
        f"✅ *Recommended Action*\n"
        f"{recommended_action}\n\n"
        f"💰 *Cost Analysis*\n"
        f"  • Intervention: {cost_of_action}\n"
        f"  • If unresolved: {cost_of_inaction}\n\n"
        f"📊 *Confidence:* {conf_pct}%   "
        f"⏱ *Response:* {response_time_seconds}s\n\n"
        f"━━━━━━━━━━━━━━━━\n"
        f"`Ref: {ref_id}`\n"
        f"`Plant: North York, ON`\n"
        f"`{timestamp}`\n"
        f"_Generated by BakeOps Command Center_"
    )

    url = _API_URL.format(token=TELEGRAM_BOT_TOKEN)
    try:
        async with httpx.AsyncClient(timeout=6.0) as client:
            resp = await client.post(url, json={
                "chat_id":    TELEGRAM_CHAT_ID,
                "text":       message,
                "parse_mode": "Markdown",
            })
            if resp.status_code == 200:
                print(f"[Telegram] ✓ Alert delivered: {ref_id}")
                return True
            else:
                print(f"[Telegram] ✗ Failed ({resp.status_code}): {resp.text[:200]}")
                return False
    except Exception as exc:
        # CRITICAL: Telegram errors must never crash the demo
        print(f"[Telegram] ✗ Error (non-fatal): {exc}")
        return False
