"""
BakeOps Telegram Alert Service
Sends a formatted alert to the plant manager when a recommendation lands.
Never raises — Telegram failure must never break the demo.
"""
from __future__ import annotations

import os
from datetime import datetime

import httpx

TELEGRAM_BOT_TOKEN: str = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID:   str = os.getenv("TELEGRAM_CHAT_ID",   "")
_API_URL = "https://api.telegram.org/bot{token}/sendMessage"


def _is_configured() -> bool:
    return bool(TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID)


def _esc(s: str) -> str:
    """Escape HTML special characters for Telegram HTML parse mode."""
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _cap(s: str, n: int = 600) -> str:
    """Truncate long text with ellipsis so the message stays readable."""
    s = s.strip()
    return s if len(s) <= n else s[:n].rsplit(" ", 1)[0] + "…"


async def send_alert(
    *,
    scenario_title: str,
    diagnosis: str,
    recommended_action: str,
    cost_of_action: str,
    cost_of_inaction: str,
    confidence: float,
    response_time_seconds: int,
) -> bool:
    """Send a formatted recommendation alert to Telegram.
    Returns True if delivered, False otherwise (silent on error).
    """
    if not _is_configured():
        print("[Telegram] Not configured — skipping alert (set TELEGRAM_BOT_TOKEN + TELEGRAM_CHAT_ID)")
        return False

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S EDT")
    ref_id    = f"BO-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    conf_pct  = int(confidence * 100) if confidence <= 1.0 else int(confidence)

    message = (
        f"🚨 <b>BAKEOPS ALERT</b>\n"
        f"━━━━━━━━━━━━━━━━\n"
        f"<b>{_esc(scenario_title)}</b>\n\n"
        f"📋 <b>Analysis</b>\n"
        f"{_esc(_cap(diagnosis, 600))}\n\n"
        f"✅ <b>Recommended Action</b>\n"
        f"{_esc(_cap(recommended_action, 400))}\n\n"
        f"💰 <b>Cost Impact</b>\n"
        f"  • Intervention cost: <b>{_esc(cost_of_action)}</b>\n"
        f"  • Cost if unresolved: <b>{_esc(cost_of_inaction)}</b>\n\n"
        f"📊 <b>Confidence:</b> {conf_pct}%   "
        f"⏱ <b>Response:</b> {response_time_seconds}s\n\n"
        f"━━━━━━━━━━━━━━━━\n"
        f"<code>Ref: {ref_id}</code>\n"
        f"<code>Plant: FGF Brands · North York, ON</code>\n"
        f"<code>{timestamp}</code>\n"
        f"<i>Generated by BakeOps Command Center</i>"
    )

    url = _API_URL.format(token=TELEGRAM_BOT_TOKEN)
    try:
        async with httpx.AsyncClient(timeout=6.0) as client:
            resp = await client.post(url, json={
                "chat_id":    TELEGRAM_CHAT_ID,
                "text":       message,
                "parse_mode": "HTML",
            })
            if resp.status_code == 200:
                print(f"[Telegram] ✓ Alert delivered: {ref_id}")
                return True
            else:
                print(f"[Telegram] ✗ Failed ({resp.status_code}): {resp.text[:300]}")
                return False
    except Exception as exc:
        print(f"[Telegram] ✗ Error (non-fatal): {exc}")
        return False
