/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas:        "#FAFAF7",
        paper:         "#FFFFFF",
        "paper-warm":  "#F6F4EF",
        ink:           "#0E0E10",
        "ink-soft":    "#1A1A1E",
        "ink-primary":   "#0E0E10",
        "ink-secondary": "#46464A",
        "ink-tertiary":  "#76767C",
        "ink-muted":     "#A8A8AE",
        "paper-primary":   "#FAFAF7",
        "paper-secondary": "#C8C8CC",
        "paper-tertiary":  "#88888E",
        accent:        "#B45309",
        "accent-soft": "#FCE9C9",
        "accent-ink":  "#78350F",
        "status-running":       "#15803D",
        "status-running-soft":  "#DCFCE7",
        "status-warning":       "#B45309",
        "status-warning-soft":  "#FEF3C7",
        "status-danger":        "#B91C1C",
        "status-danger-soft":   "#FEE2E2",
        "status-info":          "#1D4ED8",
        "status-info-soft":     "#DBEAFE",
        "agent-orchestrator": "#0E0E10",
        "agent-maintenance":  "#B45309",
        "agent-supply":       "#1D4ED8",
        "agent-recipe":       "#6D28D9",
      },
      fontFamily: {
        display: ["Fraunces", "Georgia", "serif"],
        sans:    ["Inter Tight", "system-ui", "sans-serif"],
        mono:    ["JetBrains Mono", "ui-monospace", "monospace"],
      },
    },
  },
  plugins: [],
};
